config/routes.rb
Rails.application.routes.draw do
  scope module: :web do
    get 'welcome/index'
    resources :articles do
      scope module: :articles do
        resources :comments
      end
      member do
        patch :moderate
      end
    end

    namespace :moderation do
      resources :articles, only: [:index, :show, :edit, :update]
    end
  end

  root 'web/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include ArticleStateMachine

  has_many :comments, dependent: :destroy
  has_many :links, inverse_of: :article
  belongs_to :category, required: false

  validates :title, presence: true,
                    length: { minimum: 5 }

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
end

app/models/article/category.rb
class Article::Category < ApplicationRecord
  has_many :articles
end

app/models/article/comment.rb
class Article::Comment < ApplicationRecord
  belongs_to :article
end

app/models/article/link.rb
class Article::Link < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "viraj", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "viraj", password: "password", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commentor, :body)
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  protect_from_forgery with: :exception
end

app/controllers/web/articles/application_controller.rb
class Web::Articles::ApplicationController < Web::ApplicationController
  def resource_article
    @resource_article ||= Article.find(params[:article_id])
  end
end

app/controllers/web/articles/comments_controller.rb
class Web::Articles::CommentsController < Web::Articles::ApplicationController
  def create
    @article = resource_article
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = resource_article
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:article_comment).permit(:commentor, :body)
  end
end

app/controllers/web/articles_controller.rb
class Web::ArticlesController < Web::ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = find_article
  end

  def new
    @article = Article.new
  end

  def edit
    @article = find_article
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = find_article

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = find_article
    @article.destroy

    redirect_to articles_path
  end

  def moderate
    article = find_article
    article.moderate

    redirect_to article
  end

  private

  def find_article
    Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, links_attributes: [:id, :url, :destroy])
  end
end

app/controllers/web/moderation/application_controller.rb
class Web::Moderation::ApplicationController < Web::ApplicationController
end

app/controllers/web/moderation/articles_controller.rb
class Web::Moderation::ArticlesController < Web::Moderation::ApplicationController
  def index
    default_search = { state_eq: 'on_moderation' }
    @q = Article.ransack(params[:q] || default_search)
    @articles = @q.result
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = ModerationArticleForm.find(params[:id])
  end

  def update
    @article = ModerationArticleForm.find(params[:id])

    if @article.update(params[:moderation_article_form])
      redirect_to moderation_article_url(@article)
    else
      render 'edit'
    end
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commentor:</strong>
  <%= comment.commentor %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<%= link_to 'Delete comment', [comment.article, comment],
method: :delete,
data: { confirm: 'Are you sure?' } %>
</p>
.........................................

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>
  <p>
    <%= form.label :commentor %><br>
    <%= form.text_field :commentor %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'All Articles', articles_path %>
      &nbsp;|&nbsp;
      <%= link_to 'Articles on moderation', moderation_articles_path(q: { state_eq: :on_moderation }) %>
    </nav>
      <%= yield %>
  </body>
</html>

app/views/web/articles/_form.html.slim
= simple_form_for @article, local: true do |f|
  = f.error_notification

  = f.input :title
  = f.input :text

  = f.simple_fields_for :links do |link|
    = render 'link_fields', f: link
  .links
    = link_to_add_association 'add link', f, :links

  = f.button :submit

  - if @article.persisted?
    = link_to 'Moderate', moderate_article_path(@article), method: :patch, class: 'button'

app/views/web/articles/_link_fields.html.slim
.nested-fields
  = f.input :url
  = link_to_remove_association "remove link", f

app/views/web/articles/index.html.erb
<h1>Articles: </h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <%= link_to 'New article', new_article_path %>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article), class: 'btn btn-default' %></td>
      <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-default' %></td>
      <td><%= link_to 'Destroy', article_path(article),
      method: :delete,
      data: { confirm: 'Are you sure?' },
      class: 'btn btn-default' %></td>
    </tr>
  <% end %>
</table>

app/views/web/articles/links/_link.html.slim
p
  strong Link:
  = link.url

app/views/web/articles/show.html.slim
p
  strong Title:
  = @article.title

p
  strong Text:
  = @article.text

h2 Comments
= render partial: "web/articles/comments/comment", collection: @article.comments

h2 Linkls
= render partial: "web/articles/links/link", collection: @article.links

h2 Add a comment:
= render partial: 'web/articles/comments/form'

= link_to 'Edit', edit_article_path(@article), class: 'btn btn-default'
= link_to 'Back', articles_path, class: 'btn btn-default'

app/views/web/moderation/articles/_form.html.slim
= simple_form_for @article, url: moderation_article_path(@article) do |form|
  = form.error_notification

  = form.input :state_event, as: :state_event, required: false
  = form.association :category

  = form.button :submit

app/views/web/moderation/articles/comments/_comment.html.erb
<p>
  <strong>Commentor:</strong>
  <%= comment.commentor %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/web/moderation/articles/comments/_form.html.erb
<%= form_with(model: @article.comments.build, url: article_comments_path(@article)) do |form| %>
  <p>
    <%= form.label :commentor %><br>
    <%= form.text_field :commentor %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/web/moderation/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', moderation_articles_path %>

app/views/web/moderation/articles/index.html.erb
<h1>Articles: </h1>

<%= search_form_for @q, url: moderation_articles_path do |f| %>
  <%= f.label :state_eq %>
  <%= f.select :state_eq, options_from_collection_for_select(Article.state_machine.states, 'name', 'human_name', params[:q] && params[:q][:state_eq]), include_blank: true %>

  <%= f.submit %>
<% end %>

<table>
  <tr>
    <th><%= sort_link(@q, :title, default_order: :asc)%></th>
    <th><%= sort_link(@q, :text)%></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', moderation_article_path(article) %></td>
      <td><%= link_to 'Edit', edit_moderation_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/web/moderation/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', moderation_articles_path %>

app/views/web/moderation/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render partial: "web/articles/comments/comment", collection: @article.comments %>

<h2>Add a comment:</h2>
<%= render partial: 'web/articles/comments/form' %>

<%= link_to 'Edit', edit_moderation_article_path(@article) %> |
<%= link_to 'Back', moderation_articles_path %>

app/views/web/welcome/index.html.erb
<h1>Blog</h1>
<%= link_to 'My Blog', articles_path %>